#! /bin/sh
# Starts and stops node red
# /etc/init.d/node-red
### BEGIN INIT INFO
# Provides:     node-red
# Required-Start:       $syslog $local_fs
# Required-Stop:        $syslog $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Node-web-server initialisation
### END INIT INFO
. /lib/lsb/init-functions

# This runs as the user called pi - please change as you require
USER=ubuntu

# The log is written to here - please make sure your user has write permissions.
LOG=/var/log/node-red.log

#Load up node web server when called
case "$1" in

start)
    if pgrep "node-red" > /dev/null
    then
        echo "Node Red already running."
    else
        echo "Starting Node Red.."
        touch $LOG
        chown $USER:$USER $LOG
        echo "" >> $LOG
        echo "Node Red service start: "$(date) >> $LOG
#        su -l $USER -c "cd ~/rasppi && screen -dmS red node-red-pi --max-old-space-size=128"
# or
        su -l $USER -c "node-red >> $LOG &"
        echo "Logging to "$LOG
    fi
;;

stop)
    echo "Stopping Red.."
#        su -l $USER -c "screen -S node-ws -X quit"
# or
    pkill -SIGINT "node-red"
    sleep 2
    echo "" >> $LOG
    echo "Node Red stop: "$(date) >> $LOG
;;

restart|force-reload)
        echo "Restarting Node-Red.."
        $0 stop
        sleep 2
        $0 start
        echo "Restarted."
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
